---
postgresql_version: "16"

mediawiki_version: "1.45.4"
mediawiki_server_name: "mwiki.kant.ru"
mediawiki_server_aliases:
  - "10.10.50.46"
mediawiki_server_url: "https://{{ mediawiki_server_name }}"
mediawiki_script_path: "/wiki"
mediawiki_site_language: "ru"
mediawiki_wiki_name: "My MediaWiki"
mediawiki_admin_user: "wikiadmin"
mediawiki_uploads_enabled: true
mediawiki_favicon_enabled: true
mediawiki_favicon_source: "kant-info.ico"
mediawiki_default_skin: "citizen"
mediawiki_citizen_enabled: true
mediawiki_citizen_version: "v3.21.0"
mediawiki_citizen_update_existing_users: true
mediawiki_ssl_mode: "selfsigned"
mediawiki_ssl_subject_alt_name: "DNS:mwiki.kant.ru,IP:10.10.50.46"
mediawiki_darkmode_enabled: true
mediawiki_darkmode_archive_url: ""

mediawiki_db_name: "mediawiki"
mediawiki_db_user: "mediawiki"
mediawiki_db_schema: "mediawiki"
mediawiki_db_host: "localhost"
mediawiki_db_port: 5432

zabbix_version: "7.4"
zabbix_agent_server: "10.10.50.135"
zabbix_agent_server_active: "{{ zabbix_agent_server }}"
zabbix_agent_hostname: "{{ inventory_hostname }}"

mediawiki_admin_password: "{{ vault_mediawiki_admin_password }}"
mediawiki_db_password: "{{ vault_mediawiki_db_password }}"
